### ISSUE TITLE
Probably one or more models failed

### ISSUE THREAD

**Issue by tezer** [sberbank-ai-lab/LightAutoML#32]
Hi, 
I am trying out LAMA, and keep bumping into this message:

```
Model Lvl_0_Pipe_2_Mod_0_TorchNN failed during ml_algo.fit_predict call.

only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Traceback (most recent call last):
  File "/home/dev/LAMAtest/AutoML/LAMA_train_test.py", line 38, in <module>
    oof_pred = automl.fit_predict(train, roles=roles)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/log_calls/log_calls.py", line 1939, in _deco_base_f_wrapper_
    ret = f(*args, **kwargs)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/lightautoml/automl/presets/tabular_presets.py", line 409, in fit_predict
    oof_pred = super().fit_predict(train, roles=roles, cv_iter=cv_iter, valid_data=valid_data)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/log_calls/log_calls.py", line 1939, in _deco_base_f_wrapper_
    ret = f(*args, **kwargs)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/lightautoml/automl/presets/base.py", line 176, in fit_predict
    result = super().fit_predict(train_data, roles, train_features, cv_iter, valid_data, valid_features)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/log_calls/log_calls.py", line 1939, in _deco_base_f_wrapper_
    ret = f(*args, **kwargs)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/lightautoml/automl/base.py", line 186, in fit_predict
    pipe_pred = ml_pipe.fit_predict(train_valid)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/log_calls/log_calls.py", line 1939, in _deco_base_f_wrapper_
    ret = f(*args, **kwargs)
  File "/home/dev/LAMAtest/venv/lib/python3.8/site-packages/lightautoml/pipelines/ml/base.py", line 131, in fit_predict
    assert len(predictions) > 0, 'Pipeline finished with 0 models for some reason.\nProbably one or more models failed'
AssertionError: Pipeline finished with 0 models for some reason.
Probably one or more models failed
```
I do not understand what I am supposed to do and where to dig.
Did it fail to produce a model? Why? Is it because the data is bad? Or I did something wrong?
Please advise.

**Comment by DESimakov** [comment]
Can you provide a minimal example to reproduce the problem?  And also give an example of LAMA config and system configuration.

**Comment by tezer** [comment]
```
#!/usr/bin/env python
# coding: utf-8
import logging
import os
import pickle
import shutil

import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

from lightautoml.automl.presets.text_presets import TabularNLPAutoML
from lightautoml.tasks import Task

TARGET_NAME = 'TARGET'  # Target column name

d = pd.read_csv('/home/dev/LAMAtest/AutoML/data.csv')
d.info()
data = pd.concat([d]*1).reset_index(drop=True)
data.info()
train, test = train_test_split(data, random_state=42)
logging.info('Data splitted. Parts sizes: train_data = {}, test_data = {}'
             .format(train.shape, test.shape))

roles = {
    'target': TARGET_NAME
}
task = Task('reg', )

automl = TabularNLPAutoML(task=task, timeout=600)
oof_pred = automl.fit_predict(train, roles=roles)
test_pred = automl.predict(test)
not_nan = np.any(~np.isnan(oof_pred.data), axis=1)

logging.debug('Check scores...')
print('OOF score: {}'.format(mean_squared_error(train[roles['target']].values[not_nan], oof_pred.data[not_nan][:, 0])))
print('TEST score: {}'.format(mean_squared_error(test[roles['target']].values, test_pred.data[:, 0])))
print('Pickle automl')

with open('automl.pickle', 'wb') as f:
    pickle.dump(automl, f)

logging.debug('Load pickled automl')
with open('automl.pickle', 'rb') as f:
    automl = pickle.load(f)

logging.debug('Predict loaded automl')
test_pred = automl.predict(test)
print('TEST score, loaded: {}'.format(mean_squared_error(test['deal_probability'].values, test_pred.data[:, 0])))

os.remove('automl.pickle')
shutil.rmtree('./models', ignore_errors=True)
```

**Comment by DESimakov** [comment]
Try to directly provide text features to the roles dict.
```
roles = {
    'target': TARGET_NAME
    'text': [TEXT_FEATURE1, TEXT_FEATURE2]
}
```

**Comment by tezer** [comment]
Ubuntu 20.04
python3.8
RAM 32GiB
AMD Ryzen 5 3600 6-Core Processor
GeForce RTX 2060

**Comment by tezer** [comment]
Even without any text features (binary values only) I get the same result.

**Comment by tezer** [comment]
here is a one line data sample:
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,11446,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

**Comment by DESimakov** [comment]
> Even without any text features (binary values only) I get the same result.

This is the reason. NLP pipeline requires at least one text feature for NN model. We will fix it in the future release. You can exclude NN model from the TabularNLPAutoML. For example:

```
automl = TabularNLPAutoML(task=task,
                          general_params = {'nested_cv': False,
                                            'use_algos': [['linear_l2', 'lgb',  'lgb_tuned', 'cb']]},
                          timeout=600)

```

Or use `TabularAutoML` from `lightautoml.automl.presets.tabular_presets import TabularAutoML`

**Comment by tezer** [comment]
Yes, it solved the problem.
Thank you very much!
